name: 'ICMS Location Recipe'
description: 'A content type and layout for publishing locations.'
type: 'Site'

install:
  # Core
  - node
  - user
  - views
  # Contrib
  - blokkli_starterkit
  - graphql_core_schema
  - tagify_user_list
  - conditional_fields
  - geolocation
  - geolocation_leaflet
  - office_hours

config:
  actions:
  # Enable the paragraph type on all node types
    field.field.node.*.field_icms_paragraphs:
      simple_config_update:
        settings.handler_settings.target_bundles.icms_layout_location: icms_layout_location
        settings.handler_settings.target_bundles_drag_drop.icms_layout_location.enabled: true
    paragraphs_blokkli.settings:
      'simpleConfigArray:append':
        property: enabled_types.node
        values: [icms_location]
  # Add the content type to the editorial workflow
    workflows.workflow.editorial:
      addNodeTypes: [icms_location]
  # Add the content type to the default view mode
  # GraphQL Core Schema
    graphql.graphql_servers.graphql:
      simple_config_update:
        schema_configuration.core_composable.fields.node.field_icms_address: field_icms_address
        schema_configuration.core_composable.fields.node.field_icms_coordinates: field_icms_coordinates
        schema_configuration.core_composable.fields.node.field_icms_opening_hours: field_icms_opening_hours
        # ** check if existing
        schema_configuration.core_composable.fields.node.field_icms_email: field_icms_email
        schema_configuration.core_composable.fields.node.field_icms_phone: field_icms_phone
        # check dependency on people
        schema_configuration.core_composable.fields.node.field_icms_people: field_icms_people

        schema_configuration.core_composable.bundles.node.icms_location.enabled: true
        schema_configuration.core_composable.fields.paragraph.field_icms_topics: field_icms_topics
        schema_configuration.core_composable.fields.paragraph.field_icms_listing_type: field_icms_listing_type
        schema_configuration.core_composable.bundles.paragraph.icms_layout_location.enabled: true
